version: "3.8"

services:
  api:
    build: .
    container_name: writer-studio-api
    environment:
      NOVEL_EVAL_PROVIDER: ${NOVEL_EVAL_PROVIDER:-openai}
      NOVEL_EVAL_MODEL: ${NOVEL_EVAL_MODEL:-gpt-4o-mini}
      NOVEL_EVAL_LANG: ${NOVEL_EVAL_LANG:-zh-CN}
      NOVEL_EVAL_LOG_LEVEL: ${NOVEL_EVAL_LOG_LEVEL:-INFO}
      NOVEL_EVAL_DB_PATH: /data/evals.db
      OLLAMA_HOST: ${OLLAMA_HOST:-http://localhost:11434}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    networks:
      - appnet
    # Ollama is external; no depends_on here

  nginx:
    image: nginx:alpine
    container_name: writer-studio-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - appnet

networks:
  appnet:
    driver: bridge